require 'tests/app/day01.rb'
require 'tests/app/day02.rb'
require 'tests/app/day03.rb'
require 'tests/app/day04.rb'
require 'tests/lib/animated_sprite.rb'
require 'tests/lib/animations.rb'
require 'tests/lib/animations/asesprite_json.rb'
require 'tests/lib/nine_slice_panel.rb'
